# This is for Release to Docker Hub via CI in GitHub Actions
ARG image_tag
FROM magikcraft/minecraft:${image_tag}

# Setup the working directory
RUN mkdir /srv/github-actions-app
WORKDIR /_server_

# Accept Minecraft EULA
RUN echo "eula=true" >> eula.txt

COPY build/ ./

CMD /_server_/start.sh
