# This is for CI testing
FROM magikcraft/minecraft:nukkit-589-jdk8

# Setup the working directory
RUN mkdir /srv/github-actions-app
WORKDIR /_server_

COPY build/* . 
COPY SMA/scriptcraft-tests scriptcraft-plugins/scriptcraft-tests

# Accept Minecraft EULA
RUN echo "eula=true" >> eula.txt

# From here: https://vsupalov.com/docker-build-time-env-values/
ARG TEST_MODE_SETTING=true
ENV TEST_MODE=$TEST_MODE_SETTING

# Run the tests
RUN /_server_/start.sh
