# This is for Release to Docker Hub via CI in GitHub Actions
ARG image_tag
FROM magikcraft/scriptcraft:${image_tag}

# Setup the working directory
WORKDIR /_server_

RUN rm plugins/*

COPY SMA/resources/plugins/* plugins/
COPY SMA/resources/plugins/MotdManager-Reloaded/config.yml plugins/MotdManager-Reloaded/config.yml

RUN mv plugins/h2.jar .

RUN  echo "#\!/bin/bash" > start.sh \
    && echo "java -cp minecraft.jar:h2.jar io.papermc.paperclip.Paperclip" >> start.sh \
    && chmod +x start.sh
