# This is for Release to Docker Hub via CI in GitHub Actions
ARG source_image_tag
FROM magikcraft/minecraft:${source_image_tag}

# Setup the working directory
RUN mkdir /srv/github-actions-app
WORKDIR /_server_

COPY build/ ./

CMD /_server_/start.sh
